// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwkmoicyugjhkqwmbkkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3a21vaWN5dWdqaGtxd21ia2t2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTA2ODksImV4cCI6MjA2MjM4NjY4OX0.hf634lzuA7SqSy7F6Mcl9JTITadwI7oKdHi9tUAlzP4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);